---
server:
  host: https://drone.jutonz.com
ingress:
  enabled: true
  hosts: ["drone.jutonz.com"]
  annotations:
    kubernetes.io/ingress.class: "nginx"
persistence:
  enabled: true
  storageClass: generic
